#!/bin/ksh

echo "DO NOT RUN - POSSIBLE FILE OVERWRITES!!"
exit

if [[ $# -eq 0 ]]
then
	echo "Syntax: mkhrds <filespec>"
	exit 1
fi

for i in $@
do
	echo "Processing $i..."
	OUT=`echo $i | sed 's/\.c/\.h/' `
	cat $i | grep '^[A-Za-z].*([^#]' > $OUT
done

